pipeline {
    agent any
    
    stages {
        stage('Test') {
            steps {
                echo 'Running tests'
            }
        }
        stage('Deploy'){
            steps {
                echo 'Deploying...'
            }
        }
    }
}
